### ISSUE TITLE
Key Combos not being converted

### ISSUE THREAD

**Issue by ButchMonkey** [Plazmaz/Duckuino#12]
I take your example -

```
DELAY 100
STRING Hello world! I am Duckuino!
ENTER
CTRL ALT DELETE
```

and receive -

```
print(F("HELLO WORLD! I AM DUCKUINO!"));

type(KEY_RETURN,false);
Keyboard.releaseAll();

type(KEY_LEFT_CTRL,false);
type(' ',false);
Keyboard.releaseAll();

```

The strings are fine and so is the single command but `CTRL ALT DELETE` is lost

**Comment by lowlevl** [comment]
I saw this i've got a fixed version of this software that i'll upload to my github :D That's work with all combos :D

**Comment by lowlevl** [comment]
Done uploaded ^^ https://github.com/Thecakeisgit/DuckuinoPlus

**Comment by Plazmaz** [comment]
@Thecakeisgit please submit your changes as a PR or fix your project to pertain to the rules specified in the MIT license.
EDIT: Just realized you are likely not using proprietary code. In that case, thank you for creating an alternative to a long dead project, don't worry about license stuff. Will link your project in the readme after I confirm it's working.
