### ISSUE TITLE
Please redirect to my git instead of Thecakegit's git

### ISSUE THREAD

**Issue by d4n5h** [Plazmaz/Duckuino#13]
My compiler is better than Thecakegit's compiler:
https://github.com/DanielShlomo/Duckuino

As your git is getting more attention it will be better if you'll switch to my compiler/converter.

Changes:
Added support for: REM,ESCAPE and REPLAY/REPEAT.
Added support for mouse movements and clicks ("MOUSEMOVE xPos,yPos,wheelPos" | "MOUSECLICK left/right/middle").
Fixed empty lines bug.
Rearranged the code and files.
Added simple Bootstrap CDN UI.
Switched to associative arrays/objects to reduce the use of For loops.
Added functionality for key combos.
Removed console.error for comands (i'll try to reimplement it back again).

**Comment by lowlevl** [comment]
I added support of REM and ESCAPE and i'll add REPEAT soon, your compiler is totally buggy:
- Compiler isn't verbose.
- Strings adding a space before all strings
- Unparsed lines are replaced by a simple space.
- Your page is wider than the screen.
- Unparsed key combos are replaced by text like 'CTRL ALT TEST' result in:

```
Keyboard.press('KEY_LEFT_CTRL');Keyboard.press('KEY_LEFT_ALT');Keyboard.press('TEST'); delay(50); Keyboard.release('KEY_LEFT_CTRL);Keyboard.release('KEY_LEFT_ALT);Keyboard.release('TEST);
```

_Note: Look the last key release, there isn't closing single quote._
_Note 2 : As you see there is single quotes, but KEY_ are constants so we MUSN'T use quotes._
- There is no releaseAll(); Just releasing all after in chain _ugly_
- There is no correct indentation, your lines are placed on the left.
- Your project isn't good documented.

![capture d ecran 2016-09-28 13 05 57](https://cloud.githubusercontent.com/assets/15341887/18911282/7a51806a-857c-11e6-8837-b373e41d5256.png)

@DanielShlomo

**Comment by Thecakeisgit** [comment]
It doesn't handle the errors, and just replace arbitrary code.

**Comment by lowlevl** [comment]
Updated @DanielShlomo @Plazmaz

**Comment by d4n5h** [comment]
1. Dude, you are going through arrays like an imbecile. Putting like 4 redundant  for-loops to find commands in the arrays, that was one of the ugliest solutions i saw in a while (no pun intended)...
2. "CTRL ALT TEST" - is not even something that you can/want to do. Please look a bit on what you are trying to do and you will realise it is terribly stupid lol. you want to use _keys_ in combos, not strings....
   Maybe you want to do something like that: "CTRL ALT t" or "CTRL ALT SHIFT a"
   And maybe then - "STRING TEST".
3. Yes, Unparsed commands are replaced _with_ space because that is basic logic.
   Parser stumbled on a unrecognised command = Parser didn't understood the command = No command was parsed = Blank space (Do i need to make this simpler for you? lol)
   You can send the error to the console, but don't make the compiler stop because of one command.
   And as i said - i've disabled the the console errors, will reimplement it later on.
4. My page is wider than the screen?? lol! i don't really care... as it's not suppose to be "pretty" or something... Anyway, your html/gui looks like a fart so don't even compare between the two. you can click "CTRL -" once to solve this.
5. "releaseAll();" is redundant if you release the keys recursively.
6. Ok i didn't make any documentation, although the code is pretty much self-explanatory.
   You can basically copy+paste your documentation of you project. You're just being petty, seriously...
7. REPEAT/REPLAY won't work on combos if you don't put the keys in the combos in one line.
8. ok, there is a problem with the keys not being constants.
9. Even with the indentation problem, my compiler is much better than yours...
   Don't even try to compare...
10. gonna fix it in a few moments...

**Comment by lowlevl** [comment]
1. No comment.
   2.What does when it do not recognises command ? "something: command not found", it's basic OMG. xD
2. Same
3. The CTRL - ? xD U can't make a good html page :P (Go check what i can do ^^ https://tpe.cak3repo.xyz/)
4. Why do you want to release key recursively ?
5. Ok
6. Hmmm and ?
7. No comment.
8. Rage/20.
   @DanielShlomo

**Comment by d4n5h** [comment]
1. I didn't say you can't write HTML, i just said that the GUI was ugly.
   Not that what i did is a piece of art lol it's just a bit better..
   I can't really take credit on the "design" as it's just a few lines of HTML...
   And anyway, the website in the link you gave doesn't look that good... lol
2. As i said, there is a need for debugging in console. I didn't said that we don't need to debug at all. i just preferred that compiler won't stop completely... like in Plazmaz's project...
3. You're correct on that we don't "need" to release the keys recursively.
   You can add a releaseAll(); after all the keys are pressed... Both solutions will work, it's not that important. but what you did with releaseAll() looks like a mess...
   You can just add it to the string in the end of the line...
4. Don't try to find errors in my code like a douchebag... make it better, like i did to yours...
   As my compiler is better you can just suggest a fix... and i'll add it...
   Your compiler lacked crucial commands that makes it almost useless if you don't customise/change it heavily.

**Comment by Plazmaz** [comment]
Alright, going to step in here. Two options for both of you:
1. I display both projects in the readme.
2. I add you both as contributors and you can collaborate on the project.
Also, please keep it civil.

**Comment by lowlevl** [comment]
I apologize, i think you can both and allright xD

**Comment by Plazmaz** [comment]
Either way, I will remove the current notice once this is resolved.

**Comment by lowlevl** [comment]
Sorry, that kinda immature x) Ok i'll try to help for your project @DanielShlomo.

**Comment by lowlevl** [comment]
How did arrived here lel x)

**Comment by Plazmaz** [comment]
@Thecakeisgit  Okay so in that case, you want me to put his repo on the front page in place of yours?

**Comment by lowlevl** [comment]
No both ^^

**Comment by Plazmaz** [comment]
Alright, is that okay with you @DanielShlomo?

**Comment by Plazmaz** [comment]
Wait wait wait... His project is a fork of yours... Why not just merge his branch and add him as a contributor?

**Comment by d4n5h** [comment]
Lets just make one git be better.
I don't really care for my credit, as it's not that important to me.
Let's just merge everything in your git as it is getting more attention.

**Comment by lowlevl** [comment]
Because i'm not in accord with some of his changes ^^

**Comment by d4n5h** [comment]
So fix it and put it on your git.... i'm not stopping you from fixing issues...

**Comment by lowlevl** [comment]
Ok i'll see ^^ But i prefer if you put issues on my repo ^^ Of what can i change to make the code better, because i like the way i made it ^^ Just i don't understand where my for loops are redundants xD

**Comment by d4n5h** [comment]
What exactly you don't understand?
My code does more with less lines and with less memory being used.
Simple.

**Comment by lowlevl** [comment]
Ok i'll see and fix into my repo :D Alright ?

**Comment by d4n5h** [comment]
Sure np

**Comment by lowlevl** [comment]
Ok done @Plazmaz remove this freaking issue x)

**Comment by d4n5h** [comment]
Here you go, i fixed everything you've pointed out.
Fixed indentation.
Fixed constants.
Even the useless strings in combos "bug" that you found...
Now you can do "CTRL ALT TEST" or even "CTRL ALT This is useless"

And i don't care for political correctness. I care for making things better.
if my "tone" puts you off then that's your problem. I don't really care.
When you contacted me and pointed out issues and fixes for the code i treated you with respect,
But when you just listed issues (most of them are non-issue) like a douche, while you could just suggest me fixes i became impatient with you...
