### ISSUE TITLE
does not handle repeat command.

### ISSUE THREAD

**Issue by Rosalie241** [Plazmaz/Duckuino#3]
Your program does not handle the repeat command at al. you can just  create a C loop with a number that will do -1 every time it loops again.

**Comment by Plazmaz** [comment]
Honestly, this was just a quick project I created ~2 years ago. I'm not actively maintaining it and the code is horrible. If you want these issues resolved, feel free to make a PR, but I'm not going to continue the development of this project, sorry.

**Comment by Rosalie241** [comment]
I don't know javascript at all. I know batch, shell script, vb.net and I am going to learn C in a week.
Anyway I understand that this was a quick project but:
If you start something you need to finish it.

**Comment by Plazmaz** [comment]
I am not obligated to maintain all of my old projects.

**Comment by Rosalie241** [comment]
Ok. Sorry if I was a little hard there, but I have autism and I am 14.
anyway kindly regards,
Tim Wanders(from the netherlands)

**Comment by Plazmaz** [comment]
No problem Tim, I also have autism :stuck_out_tongue_winking_eye: If you ever want to chat, feel free to email me or add me on skype(dylanisawesome11). Thanks for your interest, and good luck in your future programming ventures.

**Comment by 0x2b3bfa0** [comment]
@tim241 @Plazmaz: Maybe you are interested in my project (unmaintained also, but maybe I can improve it). https://github.com/crushedice2000/python-duckencode
